package by.bsuir.oop.shytsikau.graphic.ui;

import by.bsuir.oop.shytsikau.graphic.FileSaveUtils;
import by.bsuir.oop.shytsikau.graphic.ScriptLanguageParser;
import by.bsuir.oop.shytsikau.graphic.api.Figure;
import by.bsuir.oop.shytsikau.graphic.api.plugins.FigureTransformer;
import by.bsuir.oop.shytsikau.graphic.api.collections.PointArray;
import by.bsuir.oop.shytsikau.graphic.api.composite.FigureSet;
import by.bsuir.oop.shytsikau.graphic.figures.RectangleBounds;
import by.bsuir.oop.shytsikau.graphic.figures.basic.LineSegment;
import by.bsuir.oop.shytsikau.graphic.api.Point;
import by.bsuir.oop.shytsikau.graphic.figures.composite.Parallelogram;
import by.bsuir.oop.shytsikau.graphic.figures.composite.Rectangle;

import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import java.util.List;

public class EditorFrame extends JFrame {

    // selected figure name for working with
    private String selectedFigureName;
    // enabling moving of figure
    private boolean mouseMoveCoordinates;
    // creating user figure
    private FigureSet figureSet = new FigureSet();
    private List<FigureTransformer> plugins;

    public EditorFrame(GraphicEditorComponent graphicEditorComponent, List<FigureTransformer> plugins) {
        this.paintPanel = graphicEditorComponent;
        this.plugins = plugins;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        scriptDialog = new JDialog();
        jScrollPane2 = new JScrollPane();
        scriptTextPane = new JTextPane();
        createScriptFigureButton = new JButton();
        jScrollPane3 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jLabel1 = new JLabel();
        nameCustomScriptTextField = new JTextField();
        jLabel2 = new JLabel();
        createDialog = new JDialog();
        createFigureButton = new JButton();
        nameCustomDialogTextField = new JTextField();
        jLabel4 = new JLabel();
        jScrollPane6 = new JScrollPane();
        figuresDialogList = new JList<>();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        point1Edit = new JTextField();
        jLabel3 = new JLabel();
        point2Edit = new JTextField();
        jLabel7 = new JLabel();
        angleEdit = new JTextField();
        jLabel8 = new JLabel();
        widthEdit = new JTextField();
        jLabel9 = new JLabel();
        heightEdit = new JTextField();
        jLabel10 = new JLabel();
        startPointEdit = new JTextField();
        addFigureButton = new JButton();
        jScrollPane4 = new JScrollPane();
        addedFiguresList = new JList<>();
        jLabel11 = new JLabel();
        editorPanel = new JPanel();
        jScrollPane1 = new JScrollPane();
        figureList = new JList<>();
        addByScriptButton = new JButton();
        addByDialogButton = new JButton();
        jLabel13 = new JLabel();
        moveButton = new JButton();
        resizeEdit = new JTextField();
        resizeButton = new JButton();
        deleteButton = new JButton();
        loadButton = new JButton();
        saveButton = new JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        pluginList = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        pluginParamsEdit = new javax.swing.JTextField();
        applyPluginButton = new javax.swing.JButton();

        scriptDialog.setSize(new java.awt.Dimension(500, 450));

        jScrollPane2.setViewportView(scriptTextPane);

        createScriptFigureButton.setText("Create");
        createScriptFigureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createScriptFigureButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("isosceles width(400) height(100) startpoint(300,300);\nrectangle width(400) height(100) startpoint(200,200);");
        jScrollPane3.setViewportView(jTextArea1);

        jLabel1.setText("Example of script:");

        jLabel2.setText("Name of custom figure:");

        GroupLayout scriptDialogLayout = new GroupLayout(scriptDialog.getContentPane());
        scriptDialog.getContentPane().setLayout(scriptDialogLayout);
        scriptDialogLayout.setHorizontalGroup(
                scriptDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(scriptDialogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(scriptDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)
                                        .addGroup(scriptDialogLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(createScriptFigureButton, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(scriptDialogLayout.createSequentialGroup()
                                                .addGroup(scriptDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel1)
                                                        .addComponent(nameCustomScriptTextField)
                                                        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        scriptDialogLayout.setVerticalGroup(
                scriptDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(scriptDialogLayout.createSequentialGroup()
                                .addContainerGap(7, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameCustomScriptTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createScriptFigureButton)
                                .addContainerGap())
        );

        createDialog.setSize(new java.awt.Dimension(500, 450));

        createFigureButton.setText("Create");
        createFigureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFigureButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Name of custom figure:");

        figuresDialogList.setModel(new AbstractListModel<String>() {
            public int getSize() { return paintPanel.getFigures().size(); }
            public String getElementAt(int i) { return paintPanel.getFigures().get(i).name(); }
        });
        figuresDialogList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                figuresDialogListValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(figuresDialogList);

        jLabel5.setText("Figure to add");

        jLabel6.setText("Point 1");

        point1Edit.setText("25,25");
        point1Edit.setEnabled(false);

        jLabel3.setText("Point 2");

        point2Edit.setText("25,70");
        point2Edit.setEnabled(false);

        jLabel7.setText("Angle");

        angleEdit.setText("45");
        angleEdit.setEnabled(false);

        jLabel8.setText("Width");

        widthEdit.setText("300");
        widthEdit.setEnabled(false);

        jLabel9.setText("Height");

        heightEdit.setText("100");
        heightEdit.setEnabled(false);

        jLabel10.setText("Start Point");

        startPointEdit.setText("250,300");

        addFigureButton.setText("Add figure");
        addFigureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFigureButtonActionPerformed(evt);
            }
        });

        addedFiguresList.setModel(new AbstractListModel<String>() {
            public int getSize() { return figureSet.getFigures().size(); }
            public String getElementAt(int i) { return figureSet.getFigures().get(i).name(); }
        });
        jScrollPane4.setViewportView(addedFiguresList);

        jLabel11.setText("Added figures");

        GroupLayout createDialogLayout = new GroupLayout(createDialog.getContentPane());
        createDialog.getContentPane().setLayout(createDialogLayout);
        createDialogLayout.setHorizontalGroup(
                createDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(createDialogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane6, GroupLayout.Alignment.LEADING)
                                        .addComponent(nameCustomDialogTextField, GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(createDialogLayout.createSequentialGroup()
                                                .addGap(0, 84, Short.MAX_VALUE)
                                                .addComponent(addFigureButton, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(createFigureButton, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(createDialogLayout.createSequentialGroup()
                                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(point2Edit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(angleEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(widthEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(heightEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(startPointEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(point1Edit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(createDialogLayout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(jScrollPane4))))
                                .addContainerGap())
        );
        createDialogLayout.setVerticalGroup(
                createDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(createDialogLayout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameCustomDialogTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(point1Edit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel11))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, createDialogLayout.createSequentialGroup()
                                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jScrollPane4, GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane6))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(createDialogLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(createFigureButton)
                                                        .addComponent(addFigureButton)))
                                        .addGroup(createDialogLayout.createSequentialGroup()
                                                .addComponent(point2Edit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(angleEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(widthEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(heightEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(startPointEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        paintPanel.setBackground(new java.awt.Color(255, 255, 255));
        paintPanel.setPreferredSize(new java.awt.Dimension(1024, 768));

        GroupLayout paintPanelLayout = new GroupLayout(paintPanel);
        paintPanel.setLayout(paintPanelLayout);
        paintPanelLayout.setHorizontalGroup(
                paintPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 1024, Short.MAX_VALUE)
        );
        paintPanelLayout.setVerticalGroup(
                paintPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 768, Short.MAX_VALUE)
        );

        paintPanel.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                if (!mouseMoveCoordinates)
                    return;
                paintPanel.getFigures().getFigure(selectedFigureName).setStartPoint(new Point(evt.getX(), evt.getY()));
                paintPanel.repaint();
                mouseMoveCoordinates = false;
            }
        });

        editorPanel.setBorder(BorderFactory.createLineBorder(null));

        figureList.setModel(new AbstractListModel<String>() {
            public int getSize() { return paintPanel.getFigures().size(); }
            public String getElementAt(int i) { return paintPanel.getFigures().get(i).name(); }
        });
        figureList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                figureListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(figureList);

        addByScriptButton.setText("Add by Script");
        addByScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addByScriptButtonActionPerformed(evt);
            }
        });

        addByDialogButton.setText("Add by Dialog");
        addByDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addByDialogButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Select figure");

        moveButton.setText("Move (click where)");
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });

        resizeEdit.setText("1");

        resizeButton.setText("Resize");
        resizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Plugins");

        pluginList.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return plugins.size(); }
            public String getElementAt(int i) { return plugins.get(i).name(); }
        });
        pluginList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                pluginListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(pluginList);

        jLabel14.setText("Plagin parameters:");

        applyPluginButton.setText("Apply");
        applyPluginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyPluginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editorPanelLayout = new javax.swing.GroupLayout(editorPanel);
        editorPanel.setLayout(editorPanelLayout);
        editorPanelLayout.setHorizontalGroup(
                editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editorPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(addByScriptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addByDialogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editorPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(loadButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(editorPanelLayout.createSequentialGroup()
                                                .addGroup(editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(moveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(resizeEdit)
                                                        .addComponent(resizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(pluginParamsEdit)
                                                        .addComponent(applyPluginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 42, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        editorPanelLayout.setVerticalGroup(
                editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editorPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moveButton)
                                .addGap(18, 18, 18)
                                .addComponent(resizeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resizeButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pluginParamsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(applyPluginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadButton)
                                .addGap(18, 18, 18)
                                .addComponent(addByDialogButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addByScriptButton)
                                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(paintPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editorPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(editorPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(paintPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void addByScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {
        scriptDialog.setVisible(true);
    }

    private void createScriptFigureButtonActionPerformed(java.awt.event.ActionEvent evt) {
        paintPanel.getFigures().add(ScriptLanguageParser.createFigure(paintPanel.getFigures(), nameCustomScriptTextField.getText(), scriptTextPane.getText()));
        refresh();
        scriptDialog.setVisible(false);
    }

    private void createFigureButtonActionPerformed(java.awt.event.ActionEvent evt) {
        figureSet.setName(nameCustomDialogTextField.getText());
        paintPanel.getFigures().add(figureSet);
        refresh();
        figureSet = new FigureSet();
        createDialog.setVisible(false);
    }

    private void addFigureButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Figure selected = paintPanel.getFigures().getFigure(figuresDialogList.getSelectedValue());
        selected = selected.clone();
        if (point1Edit.isEnabled()) {
            String[] point1str = point1Edit.getText().split(",");
            String[] point2str = point2Edit.getText().split(",");
            selected.setPoints(new PointArray(Arrays.asList(new Point(Integer.parseInt(point1str[0]), Integer.parseInt(point1str[1])), new Point(Integer.parseInt(point2str[0]), Integer.parseInt(point2str[1])))));
        }
        if (heightEdit.isEnabled()) {
            selected.setHeight(Integer.parseInt(heightEdit.getText()));
        }
        if (widthEdit.isEnabled()) {
            selected.setWidth(Integer.parseInt(widthEdit.getText()));
        }
        if (angleEdit.isEnabled()) {
            selected.setAngle(Double.parseDouble(angleEdit.getText()));
        }
        if (startPointEdit.isEnabled()) {
            String[] startPointStr = startPointEdit.getText().split(",");
            selected.setStartPoint(new Point(Integer.parseInt(startPointStr[0]), Integer.parseInt(startPointStr[1])));
        }
        figureSet.addFigure(selected);
        addedFiguresList.updateUI();
    }

    private void addByDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {
        createDialog.setVisible(true);
        figuresDialogList.updateUI();
        figureSet = new FigureSet();
    }

    private void figuresDialogListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        point1Edit.setEnabled(false);
        point2Edit.setEnabled(false);
        angleEdit.setEnabled(false);
        widthEdit.setEnabled(false);
        heightEdit.setEnabled(false);
        startPointEdit.setEnabled(true);
        Figure selected = paintPanel.getFigures().getFigure(figuresDialogList.getSelectedValue());
        if (selected instanceof LineSegment) {
            point1Edit.setEnabled(true);
            point2Edit.setEnabled(true);
            startPointEdit.setEnabled(false);
        }
        if (selected instanceof RectangleBounds) {
            widthEdit.setEnabled(true);
            heightEdit.setEnabled(true);
        }
        if (selected instanceof Parallelogram) {
            angleEdit.setEnabled(true);
        }
        if (selected instanceof Rectangle) {
            angleEdit.setEnabled(false);
        }
    }

    private void figureListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        deleteButton.setEnabled(false);
        this.selectedFigureName = figureList.getSelectedValue();
        if (selectedFigureName.startsWith("custom")) {
            deleteButton.setEnabled(true);
        }
    }

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        mouseMoveCoordinates = true;
    }

    private void resizeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        paintPanel.getFigures().getFigure(selectedFigureName).resize(Double.parseDouble(resizeEdit.getText()));
        paintPanel.repaint();
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Figure toDelete = paintPanel.getFigures().getFigure(selectedFigureName);
        paintPanel.getFigures().remove(toDelete);
        refresh();
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        FileSaveUtils.save(paintPanel.getFigures());
    }

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {
        FileSaveUtils.load(paintPanel.getFigures());
        refresh();
    }

    private void pluginListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        pluginParamsEdit.setText(plugins.get(pluginList.getSelectedIndex()).getExampleParams());
    }

    private void applyPluginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        FigureTransformer selectedPlugin = plugins.get(pluginList.getSelectedIndex()).clone();
        Figure newFigure = selectedPlugin.init(paintPanel.getFigures().getFigure(selectedFigureName), pluginParamsEdit.getText());
        paintPanel.getFigures().add(newFigure);
        refresh();
    }

    private void refresh() {
        figureList.updateUI();
        paintPanel.repaint();
    }

    // Variables declaration - do not modify
    private JButton addByDialogButton;
    private JButton addByScriptButton;
    private JButton addFigureButton;
    private JList<String> addedFiguresList;
    private JTextField angleEdit;
    private javax.swing.JButton applyPluginButton;
    private JDialog createDialog;
    private JButton createFigureButton;
    private JButton createScriptFigureButton;
    private JButton deleteButton;
    private JPanel editorPanel;
    private JList<String> figureList;
    private JList<String> figuresDialogList;
    private JTextField heightEdit;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel13;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private JScrollPane jScrollPane6;
    private JTextArea jTextArea1;
    private JButton loadButton;
    private JButton moveButton;
    private JTextField nameCustomDialogTextField;
    private JTextField nameCustomScriptTextField;
    private GraphicEditorComponent paintPanel;
    private javax.swing.JList<String> pluginList;
    private javax.swing.JTextField pluginParamsEdit;
    private JTextField point1Edit;
    private JTextField point2Edit;
    private JButton resizeButton;
    private JTextField resizeEdit;
    private JButton saveButton;
    private JDialog scriptDialog;
    private JTextPane scriptTextPane;
    private JTextField startPointEdit;
    private JTextField widthEdit;
}
